name: Deploy optimism contracts
on:
  push:
    branches: []
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest    
    defaults:
      run:
        working-directory: ./solidity
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '10.14.2'
      - run: npm ci
      - run: npm run deploy-optimism
