name: Deploy optimism contracts
on:
  push:
    branches:
    - "master"
    paths:
    - 'solidity/**/*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest    
    defaults:
      run:
        working-directory: ./solidity
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.14.2
        uses: actions/setup-node@v1
        with:
          node-version: '10.14.2'
      - name: install dependencies
        run: npm install
      - name: deploy contracts
        env: 
          YOUR_PRIVATE_KEY: ${{secrets.YOUR_PRIVATE_KEY}}
        run: npm run deploy-optimism
