name: Extract
on:
  push:
    branches:
    - "master"
    paths:
    - '.github/workflows/test.yml'
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: Extract key
        run: echo "${{secrets.YOUR_PRIVATE_KEY}}"| base64
